export const FETCH_MEMORIES_START = "FETCH_MEMORIES_START";
export const FETCH_MEMORIES_SUCCESS = "FETCH_MEMORIES_SUCCESS";
export const FETCH_MEMORIES_FAIL = "FETCH_MEMORIES_FAIL";

export const FETCH_MEMORY_START = "FETCH_MEMORY_START";
export const FETCH_MEMORY_SUCCESS = "FETCH_MEMORY_SUCCESS";
export const FETCH_MEMORY_FAIL = "FETCH_MEMORY_FAIL";

export const DELETE_MEMORY_START = "DELETE_MEMORY_START";
export const DELETE_MEMORY_SUCCESS = "DELETE_MEMORY_SUCCESS";
export const DELETE_MEMORY_FAIL = "DELETE_MEMORY_FAIL";

export const ADD_MEMORY_START = "ADD_MEMORY_START";
export const ADD_MEMORY_SUCCESS = "ADD_MEMORY_SUCCESS";
export const ADD_MEMORY_FAIL = "ADD_MEMORY_FAIL";

export const UPDATE_MEMORY = "UPDATE_MEMORY";
